package com.moriarty.morimvcandroid.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.moriarty.morimvcandroid.module.news_category.CategoryEntity;
import com.moriarty.morimvcandroid.model.entities.FunctionBean;

import com.moriarty.morimvcandroid.greendao.db.CategoryEntityDao;
import com.moriarty.morimvcandroid.greendao.db.FunctionBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryEntityDaoConfig;
    private final DaoConfig functionBeanDaoConfig;

    private final CategoryEntityDao categoryEntityDao;
    private final FunctionBeanDao functionBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryEntityDaoConfig = daoConfigMap.get(CategoryEntityDao.class).clone();
        categoryEntityDaoConfig.initIdentityScope(type);

        functionBeanDaoConfig = daoConfigMap.get(FunctionBeanDao.class).clone();
        functionBeanDaoConfig.initIdentityScope(type);

        categoryEntityDao = new CategoryEntityDao(categoryEntityDaoConfig, this);
        functionBeanDao = new FunctionBeanDao(functionBeanDaoConfig, this);

        registerDao(CategoryEntity.class, categoryEntityDao);
        registerDao(FunctionBean.class, functionBeanDao);
    }
    
    public void clear() {
        categoryEntityDaoConfig.clearIdentityScope();
        functionBeanDaoConfig.clearIdentityScope();
    }

    public CategoryEntityDao getCategoryEntityDao() {
        return categoryEntityDao;
    }

    public FunctionBeanDao getFunctionBeanDao() {
        return functionBeanDao;
    }

}
